name: tests

on: [push]

jobs:
  test-python-37:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: make ci-install
    - name: Test with pytest
      run: make tests
